name: pravasa
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  android_intent_plus: ^3.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.2.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  speech_to_text: ^7.0.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.png
  android: true
  ios: true
  image_size: 300  # Increase this value to make the logo larger
  android_gravity: center  # Centers the image on Android



flutter:
  uses-material-design: true

  assets:
    - assets/icon/splash_logo.png
